require("dotenv").config();
const express = require("express");
const routes = require("./routes");
const swaggerUi = require('swagger-ui-express');
const YAML = require('yamljs');
const path = require('path');
const app = express();
app.use(express.json());
const swaggerDocument = YAML.load(path.join(__dirname, './appointment.swagger.yaml'));
routes(app);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server chạy tại http://localhost:${PORT}`));